// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `publisher`, `subscriber`, `watch_stream`
// These types are ignored because they are not used by any `pub` functions: `Pub`, `SubscriptionManager`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `emap`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`, `send`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<T>>
abstract class T implements RustOpaqueInterface {}

abstract class MapErr {
  Future<T> emap();
}
